### ISSUE TITLE
Tried this sample and when running locally error

### ISSUE THREAD

**Issue by evillgenius75** [kedacore/sample-javascript-eventhub-azure-function#2]
I am running the azure function locally and I get this error:

```
Executed 'Functions.EventHubTrigger' (Failed, Id=9c30115a-3b60-4a66-b6d1-d430b35f99fc)
[2/4/20 9:50:20 PM] System.Private.CoreLib: Exception while executing function: Functions.EventHubTrigger. Microsoft.Azure.WebJobs.Script: Did not find any initialized language workers.
```
I am running Core Tools 2.7.210, on Mac OSX 10.15.2 with the node/javascript setup when did `func init . --docker` and Azure Event Hubs Trigger when i did the `func new`

**Comment by anirudhgarg** [comment]
Hey @evillgenius75 looks like there is no language worker found. Can you start over and run "func init" and then choose a runtime  lanuage.  Then func new choose eventhubtrigger template, Make the changes you need for settings and then run func host start and see how that works. You can then run func init . --docker to produce the docker file
